import type { Competition, CompLeaderboardEntry } from "./types";

export const COMP_TYPES = [
  "Crypto",
  "Bank Transfer",
  "Bills & Airtime",
  "Cross-border",
  "Referrals",
  "Custom",
];

export const COMP_CATEGORIES: Record<string, string[]> = {
  "Crypto": ["USDT", "USDC", "BTC", "ETH", "All Crypto"],
  "Bank Transfer": ["NGN Transfer", "USD Wire", "GBP Faster Payments", "EUR SEPA", "All Transfers"],
  "Bills & Airtime": [
    "Airtime (MTN, Airtel, GLO, 9mobile)",
    "Data Bundles",
    "Electricity Bills",
    "TV Subscriptions",
    "Internet Services",
    "Water Bills",
    "All Bills",
  ],
  "Cross-border": [
    "Ghana (GHS)",
    "Kenya (KES)",
    "South Africa (ZAR)",
    "United Kingdom (GBP)",
    "Europe (EUR)",
    "United States (USD)",
    "All Destinations",
  ],
  "Referrals": [
    "App Downloads",
    "KYC Tier 2 Verification",
    "First Deposit",
    "First Transaction",
    "All Referrals",
  ],
  "Custom": ["Custom Target"],
};

export const INITIAL_COMPETITIONS: Competition[] = [
  {
    id: "c1",
    title: "Crypto Rain Season 3",
    type: "Crypto — USDT, USDC",
    typeCategory: "Crypto",
    typeSubcategory: "USDT",
    typeSubcategories: ["USDT", "USDC"],
    tagline: "Trade crypto and win top prizes!",
    season: "Season 3",
    prizePool: 1500000,
    status: "active",
    start: "2026-08-01",
    end: "2026-09-30",
    participants: 1420,
    accentColor: "#7B3FE4",
    entryCondition: "auto",
    minQualifyingAmt: 10000,
    visibility: "public",
    notes: "Q3 major crypto campaign",
    referralBonus: 1000,
    prizeTiers: [
      { rankFrom: 1, rankTo: 1, label: "1st Place", prize: 500000 },
      { rankFrom: 2, rankTo: 2, label: "2nd Place", prize: 300000 },
      { rankFrom: 3, rankTo: 3, label: "3rd Place", prize: 200000 },
      { rankFrom: 4, rankTo: 10, label: "Top 10", prize: 50000 },
    ],
  },
  {
    id: "c2",
    title: "Bills Bonanza",
    type: "Bills & Airtime — Electricity Bills, Data Bundles",
    typeCategory: "Bills & Airtime",
    typeSubcategory: "Electricity Bills",
    typeSubcategories: ["Electricity Bills", "Data Bundles"],
    tagline: "Pay bills & get rewarded",
    season: "Season 1",
    prizePool: 500000,
    status: "active",
    start: "2026-08-15",
    end: "2026-09-15",
    participants: 890,
    accentColor: "#F59E0B",
    entryCondition: "auto",
    minQualifyingAmt: 2000,
    visibility: "public",
    notes: "Promote bill payment adoption",
    prizeTiers: [
      { rankFrom: 1, rankTo: 1, label: "1st Place", prize: 200000 },
      { rankFrom: 2, rankTo: 2, label: "2nd Place", prize: 100000 },
      { rankFrom: 3, rankTo: 5, label: "Top 5", prize: 50000 },
      { rankFrom: 6, rankTo: 10, label: "Top 10", prize: 10000 },
    ],
  },
  {
    id: "c3",
    title: "Global Transfer Sprint",
    type: "Cross-border — United Kingdom (GBP), Europe (EUR)",
    typeCategory: "Cross-border",
    typeSubcategory: "United Kingdom (GBP)",
    typeSubcategories: ["United Kingdom (GBP)", "Europe (EUR)"],
    tagline: "Highest cross-border volume wins",
    season: "Season 2",
    prizePool: 800000,
    status: "ended",
    start: "2026-07-01",
    end: "2026-08-01",
    participants: 610,
    accentColor: "#06B6D4",
    entryCondition: "auto",
    minQualifyingAmt: 50000,
    visibility: "public",
    notes: "Ended — pending approval & disbursement",
    prizeTiers: [
      { rankFrom: 1, rankTo: 1, label: "1st Place", prize: 400000 },
      { rankFrom: 2, rankTo: 2, label: "2nd Place", prize: 200000 },
      { rankFrom: 3, rankTo: 5, label: "Top 5", prize: 66666 },
    ],
  },
  {
    id: "c4",
    title: "Mega Referral Challenge",
    type: "Referrals — All Referrals",
    typeCategory: "Referrals",
    typeSubcategory: "All Referrals",
    typeSubcategories: ["All Referrals"],
    tagline: "Invite friends and top the board",
    season: "Season 1",
    prizePool: 1000000,
    status: "upcoming",
    start: "2026-10-01",
    end: "2026-11-01",
    participants: 0,
    accentColor: "#10B981",
    entryCondition: "auto",
    minQualifyingAmt: 0,
    visibility: "public",
    notes: "Q4 growth booster",
    referralBonus: 500,
    prizeTiers: [
      { rankFrom: 1, rankTo: 1, label: "1st Place", prize: 400000 },
      { rankFrom: 2, rankTo: 2, label: "2nd Place", prize: 250000 },
      { rankFrom: 3, rankTo: 3, label: "3rd Place", prize: 150000 },
      { rankFrom: 4, rankTo: 10, label: "Top 10", prize: 28571 },
    ],
  },
];

export const INITIAL_LEADERBOARDS: Record<string, CompLeaderboardEntry[]> = {
  c1: [
    { rank: 1, userId: "u101", user: "Tunde Ednut", metric: 45000, metricLabel: "USDT Volume", trend: "up" },
    { rank: 2, userId: "u102", user: "Amaka Okafor", metric: 38500, metricLabel: "USDT Volume", trend: "up" },
    { rank: 3, userId: "u103", user: "Kelechi Iheanacho", metric: 31000, metricLabel: "USDT Volume", trend: "down" },
    { rank: 4, userId: "u104", user: "Chioma Adeleke", metric: 27400, metricLabel: "USDT Volume", trend: "up" },
    { rank: 5, userId: "u105", user: "Emeka Junior", metric: 22100, metricLabel: "USDT Volume", trend: "down", flagged: true, flagNote: "Unusual volume spike in short timeframe" },
  ],
  c2: [
    { rank: 1, userId: "u201", user: "Bisi Akande", metric: 145000, metricLabel: "₦ Bills Paid", trend: "up" },
    { rank: 2, userId: "u202", user: "David Mark", metric: 112000, metricLabel: "₦ Bills Paid", trend: "up" },
    { rank: 3, userId: "u203", user: "Funke Akindele", metric: 98000, metricLabel: "₦ Bills Paid", trend: "up" },
  ],
  c3: [
    { rank: 1, userId: "u301", user: "Segun Arinze", metric: 8500, metricLabel: "GBP Transferred", trend: "up" },
    { rank: 2, userId: "u302", user: "Grace Egbagbe", metric: 6200, metricLabel: "GBP Transferred", trend: "down" },
    { rank: 3, userId: "u303", user: "Femi Otedola", metric: 4900, metricLabel: "GBP Transferred", trend: "up" },
  ],
};
